git_commit = `git rev-parse HEAD | cut -c -7 || echo ${DRONE_COMMIT_SHA}`
git_tag = `git describe --tags \`git rev-list --tags --max-count=1)\``

binary_name=statuscentral
config_file=statuscentral.local.yaml

# Build the statuscentral binary.
build: clean
	@CGO_ENABLED=0 go build -v -a -o ${binary_name} main.go
	@cp ./${config_file} ${binary_name}.yaml

# Delete all artifacts generated by the build routines.
clean:
	@docker-compose down
	@rm -f ${binary_name} ${binary_name}.yaml

# Build the statuscentral docker image.
docker:
	docker build -t fleetcommand:$(git_commit) .

# Build and execute the statuscentral binary.
run: build
	./${binary_name}

# Deploy all components related to statuscentral and statuscentral locally via docker-compose.
start:
	@docker-compose up -d --build